### ISSUE TITLE
A BUG

### ISSUE THREAD

**Issue by yangop8** [gospodima/Extended-SimGNN#1]
There is something wrong with `mean = scatter_('mean', x, batch, size)` in function _forward_ in **layer.py**.
When compute scatter_add, the *dim* is computed wrong.
How could I fix that bug? Wait for your response.

Best Wishes!

**Comment by yangop8** [comment]
I guess you should replace `mean = scatter_('mean', x, batch, size)` by `mean = scatter_('mean', x, batch, dim_size=size)` and `return scatter_('add', weighted, batch, size)` by `return scatter_('add', weighted, batch, dim_size=size)`. If not, the *size* is default the definition of *dim*(i.e., the input dimension) rather than *dim_size*(i.e., the output dimension).
After that, the code can run normally.
Please comment about this.

**Comment by gospodima** [comment]
@yangop8, thanks for this note. Proposed fix has been added.
