### ISSUE TITLE
About "Fully Connected Layers" Settings

### ISSUE THREAD

**Issue by Sangs3112** [gospodima/Extended-SimGNN#11]
Hi, I noticed that in the SimGNN paper, there was a setting for FCL, "use 4 fully connected layers to reduce the dimension of the concatenated results from the NTN module, from 32 to 16, 16 to 8, 8 to 4, and 4 to 1." However, I found that in this code, there are only two fully connected layers, which are 32 --> 16, and 16--> 1. 
When I modify the code according to the Settings in the paper, I find that the performance is worse by ten times, I don't know why, isn't the general Settings in the paper better?
Here is the code in this Repository
![lu1](https://github.com/gospodima/Extended-SimGNN/assets/53257990/16e860a3-85d8-4cd8-8166-8c5154b7db71)
![lu2](https://github.com/gospodima/Extended-SimGNN/assets/53257990/308e2e93-ab29-4179-ad43-c7e011c74a26)

Here is my code
![my1](https://github.com/gospodima/Extended-SimGNN/assets/53257990/f150443b-af96-49b7-9344-abbbaccff794)
![my2](https://github.com/gospodima/Extended-SimGNN/assets/53257990/e0b398e1-9349-4f81-a523-db10b95a1df6)

**Comment by gospodima** [comment]
Hi @Sangs3112,

If I correctly remember, my tests with more FCLs didn't bring markable improvements in results and I kept only 2 layers.

**Comment by Sangs3112** [comment]
> 
Thank you for your reply.
Yes, you are right, and I am wondering why the performance was reduced according to the Settings of the paper. In addition, I found that even if I kept only two FCLs  and used GIN with better performance than GCN, the results were still not comparable to the results in the paper.

**Comment by gospodima** [comment]
There were several issues regarding configuration, achieved performance and how they are comparable to results in paper: #3, #5.
For example, pairwise node comparison caused significant overfitting effect for me.
You can take a look on them.
