### ISSUE TITLE
The potential bug in the "calculate_prec_at_k"

### ISSUE THREAD

**Issue by canqin001** [gospodima/Extended-SimGNN#4]
Hi,

Your code is very helpful for this topic. While I might find a bug on the function "calculate_prec_at_k" for recall acc calculation. In the "calculate_prec_at_k", there are two potential bugs:

1. In "calculate_prec_at_k" (line 47-48 of "utils.py"), the correct way should be 
    best_k_pred = prediction.argsort()[:k]  -> best_k_pred = prediction.argsort()[:,:,-1][:k]
    best_k_target = target.argsort()[:k] -> best_k_target = target.argsort()[:,:,-1][:k]
The decrese order is correct as the normalized GED is in [1, 0] and 1 means the exactly same. 

2. Also in the "calculate_prec_at_k", there might be multiple ground truth graphs whose quantity is larger than k. In other words, if setting k as 10, the 10th, 11th and 12th similar graphs might share the same (equal) ground truth GED score with the predict graph. In this case, the ground truth graphs should be larger than k, i.e. k=10,  and set a threshold to select the other graphs to the "best_k_target". Here are my solutions:

def _calculate_prec_at_k(k, target):
    target_increase = np.sort(target)
    target_value_sel = (target_increase <= target_increase[k-1]).sum()
    if target_value_sel > k:
        best_k_target = target.argsort()[:target_value_sel]
    else:
        best_k_target = target.argsort()[:k]
    return best_k_target

**Comment by gospodima** [comment]
Hi @canqin001,

thanks for making an issue.
Regarding the first point you should keep in mind that at calculate_prec_at_k we have not a normalized ged, but a similarity score, which is defined as e^(-x), where x is normalized ged. Check "4.2  Data Preprocessing" in the original paper to see definition of similarity score.

Considering the second point I am not sure that I correctly understood your point. Based on the definition of precision@k, which is also described in the paper ("Precision at k is computed by taking the intersection of the predicted top k results and the ground-truth top k results divided by k"), I don't see the reason, why the threshold should be increased even if we have same scores for k-th, (k+1)th, (k+2)th ... graphs. Maybe you could clarify this point?

**Comment by canqin001** [comment]
Hi, thanks for your reply.

For the first point, if **x is the normalized ged, x=0 should be the most similar case and it also means exp^(-0) = 1**. So, the after the processing, the similarity score of the exactly similar graph pairs will be 1 and the most dissimilar ones will be 0. Therefore, in my opinion, there should be the decreasing order to select most similar graph truth pairs. And the prediction.argsort()[:k] is the increasing order.

For the second point, I notice a phenomenon that there are multiple k-th ground truth target graphs. I mean, if the k is 10, and the similarity score of the 10-th similar target graph might be 0.95. While, **there might be more than 1 target graphs whose similarity score is 0.95**. So, all these target graphs need to be considered as the ground truth target graph.

**Comment by gospodima** [comment]
Ok, now I think I understood your points. I agree. After I check some staff, I will most probably apply changes proposed by you.

Thank you for reporting these bugs :)

**Comment by gospodima** [comment]
It was a long time before I worked on the project again, but just to let you know - fixes are done. Thanks again for reporting, @canqin001.
