### ISSUE TITLE
About the performance reported in the original paper[SimGNN]

### ISSUE THREAD

**Issue by wondervictor** [gospodima/Extended-SimGNN#5]
Hi, thanks for your contribution to this PyTorch implementation of SimGNN. I'm concerned about whether the provided code of this repo can reach the performance reported in the original SimGNN paper, i.e. 1.189 mse(10^-3) for AIDS dataset.

**Comment by gospodima** [comment]
Hi @wondervictor,

During my experiments I coud reach around 2.5 mse(10^-3) for AIDS. However, on LINUX I received 1.047 and with longer training it should be even better.

**Comment by wondervictor** [comment]
Hi @gospodima , thanks for your quick reply!
Have you ever analyzed performance gap between this implementation and the original released code?
I've tried kinds of experimental settings (modules, learning schedules) with this implementation while I cannot reach the performance reported in the paper.  
Several papers mention that they evaluate the similarities between testing graphs(queries) and the whole dataset (including training set and testing set **?**). Unfortunately, the GED of testing graphs is missing.

**Comment by gospodima** [comment]
When I worked on my thesis, I couldn't manage to set up the tensorflow implementation referenced in the original paper, so I didn't test that code. I didn't go too deep in analysis regarding performance gap.

> Several papers mention that they evaluate the similarities between testing graphs(queries) and the whole dataset (including training set and testing set ?). Unfortunately, the GED of testing graphs is missing.

If I correctly remember, in my implementation train-train graph pairs were used for training and train-test graph pairs were used for evaluation.
