### ISSUE TITLE
About how to test a new dataset？

### ISSUE THREAD

**Issue by Cain399** [gospodima/Extended-SimGNN#8]
Hello, your code is very useful to testing the datasets of ADIS. Now, I have a new datasets. If i want to test the new datasets, need I create a new class like GEDDataset using pyG? In that case, could you give me some suggestion and notice about creating new datasets? I would appreciate it if you could reply !

**Comment by gospodima** [comment]
Hello @Cain399 

>  If i want to test the new datasets, need I create a new class like GEDDataset using pyG?

Yes. Unfortunately, current implementation does not support any easy way to test custom datasets.
I can't suggest much about creating new datasets. You can take a look on GEDDataset source [code](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/ged_dataset.html#GEDDataset) and try to rewrite it.
Probably, the easiest way would be to store your dataset in the same format that is used for original datasets (in source code you can find url's for that) and rewrite `download` method.
